# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('IUPAC_name', models.CharField(blank=True, max_length=2048)),
            ],
        ),
    ]
