# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='bindingdb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='cas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='chembl_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='cid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='drug_groups',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='drug_status',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='drugbank_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='first_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compound',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mol_images'),
        ),
        migrations.AddField(
            model_name='compound',
            name='last_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compound',
            name='mol_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='pathway_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
