# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0005_auto_20170426_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniprotinfo',
            name='compounds',
            field=models.ManyToManyField(blank=True, to='related_info.Compound'),
        ),
    ]
