# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 01:56
from __future__ import unicode_literals

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0008_auto_20170519_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='mol',
            field=django_rdkit.models.fields.MolField(blank=True, null=True),
        ),
    ]
