# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0009_auto_20170519_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='mol',
        ),
    ]
