# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 02:13
from __future__ import unicode_literals

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0010_remove_compound_mol'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='mol',
            field=django_rdkit.models.fields.MolField(blank=True, null=True),
        ),
    ]
