# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0012_compound_bfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='related_compounds',
            field=models.ManyToManyField(blank=True, related_name='_compound_related_compounds_+', to='related_info.Compound'),
        ),
    ]
