# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0013_compound_related_compounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeggProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniprotAllPathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniprotDBCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='uniprotinfo',
            name='kegg_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uniprotinfo',
            name='uniprot_chembl_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uniprotinfo',
            name='uniprot_descriptor',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='uniprotinfo',
            name='uniprot_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='uniprotdbcompound',
            name='uniprot_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_info.UniprotInfo'),
        ),
        migrations.AddField(
            model_name='uniprotallpathway',
            name='uniprot_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_info.UniprotInfo'),
        ),
        migrations.AddField(
            model_name='keggprotein',
            name='keggname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='related_info.UniprotInfo'),
        ),
    ]
