# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0014_auto_20171015_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniprotinfo',
            name='uniprot_descriptor',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
