# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0015_auto_20171015_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniprotallpathway',
            name='pathway_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uniprotallpathway',
            name='pathway_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
