# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_info', '0021_uniprotdbcompound_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
